// <auto-generated />
using System;
using HumansVsZombies_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HumansVsZombies_Backend.Migrations
{
    [DbContext(typeof(HvZDbContext))]
    [Migration("20220915061046_initial-migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HumansVsZombies_Backend.Models.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ChatTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHumanGlobal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsZombieGlobal")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("SquadId")
                        .HasColumnType("int");

                    b.HasKey("ChatId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SquadId");

                    b.ToTable("Chat");

                    b.HasData(
                        new
                        {
                            ChatId = 1,
                            ChatTime = new DateTime(2022, 9, 15, 8, 10, 46, 68, DateTimeKind.Local).AddTicks(6533),
                            GameId = 1,
                            IsHumanGlobal = false,
                            IsZombieGlobal = false,
                            Message = "Who is the zombie today?",
                            PlayerId = 1
                        },
                        new
                        {
                            ChatId = 2,
                            ChatTime = new DateTime(2022, 9, 15, 8, 10, 46, 68, DateTimeKind.Local).AddTicks(7004),
                            GameId = 1,
                            IsHumanGlobal = true,
                            IsZombieGlobal = false,
                            Message = "Hello",
                            PlayerId = 1,
                            SquadId = 4
                        });
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GameState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("NwLat")
                        .HasColumnType("float");

                    b.Property<double?>("NwLng")
                        .HasColumnType("float");

                    b.Property<double?>("SeLat")
                        .HasColumnType("float");

                    b.Property<double?>("SeLng")
                        .HasColumnType("float");

                    b.HasKey("GameId");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            Description = "Intresting game",
                            GameName = "Left for Dead",
                            GameState = "Registration",
                            NwLat = -26.66386,
                            NwLng = 25.283757999999999,
                            SeLat = -16.66686,
                            SeLng = 17.96686
                        },
                        new
                        {
                            GameId = 2,
                            Description = "Absorbing game",
                            GameName = "Walking Dead",
                            GameState = "In progress",
                            NwLat = -16.66386,
                            NwLng = 15.283758000000001,
                            SeLat = -6.6668599999999998,
                            SeLng = 7.9668599999999996
                        },
                        new
                        {
                            GameId = 3,
                            Description = "Fascinating game",
                            GameName = "Days Gone",
                            GameState = "Complete",
                            NwLat = -20.263860000000001,
                            NwLng = 21.283358,
                            SeLat = -13.66686,
                            SeLng = 12.99686
                        });
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.Kill", b =>
                {
                    b.Property<int>("KillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("KillerId")
                        .HasColumnType("int");

                    b.Property<double?>("Lat")
                        .HasColumnType("float");

                    b.Property<double?>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("Story")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeOfDeath")
                        .HasColumnType("datetime2");

                    b.Property<int>("VictimId")
                        .HasColumnType("int");

                    b.HasKey("KillId");

                    b.HasIndex("GameId");

                    b.HasIndex("KillerId");

                    b.HasIndex("VictimId")
                        .IsUnique();

                    b.ToTable("Kill");

                    b.HasData(
                        new
                        {
                            KillId = 1,
                            GameId = 1,
                            KillerId = 1,
                            Lat = -24.66206,
                            Lng = 15.213158,
                            Story = "The zombie tagged the Human when she was eating",
                            TimeOfDeath = new DateTime(2022, 10, 30, 14, 32, 21, 0, DateTimeKind.Unspecified),
                            VictimId = 2
                        });
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.Mission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHumanVisible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsZombieVisible")
                        .HasColumnType("bit");

                    b.Property<string>("MissionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("MissionId");

                    b.HasIndex("GameId");

                    b.ToTable("Mission");

                    b.HasData(
                        new
                        {
                            MissionId = 1,
                            Description = "Try your best to collect five types of medicine. Good Luck!",
                            EndTime = new DateTime(2022, 11, 30, 18, 32, 20, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            IsHumanVisible = true,
                            IsZombieVisible = false,
                            MissionName = "Collect medicine",
                            StartTime = new DateTime(2022, 11, 30, 17, 32, 20, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MissionId = 2,
                            Description = "Try your best to collect five types of powerpotion. Good Luck!",
                            EndTime = new DateTime(2022, 11, 30, 15, 32, 20, 0, DateTimeKind.Unspecified),
                            GameId = 1,
                            IsHumanVisible = false,
                            IsZombieVisible = true,
                            MissionName = "Collect powerpotion",
                            StartTime = new DateTime(2022, 11, 30, 14, 32, 20, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MissionId = 3,
                            Description = "Try your best to collect as many weapons as possible. Good Luck!",
                            EndTime = new DateTime(2022, 11, 30, 21, 32, 20, 0, DateTimeKind.Unspecified),
                            GameId = 2,
                            IsHumanVisible = true,
                            IsZombieVisible = false,
                            MissionName = "Collect weapons",
                            StartTime = new DateTime(2022, 11, 30, 20, 32, 20, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BiteCode")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHuman")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPatientZero")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PlayerId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            BiteCode = 23234,
                            GameId = 1,
                            IsHuman = true,
                            IsPatientZero = false,
                            UserId = "c208f8b8-22bb-464c-93c9-0e011f4d827f"
                        },
                        new
                        {
                            PlayerId = 2,
                            BiteCode = 17154,
                            GameId = 1,
                            IsHuman = false,
                            IsPatientZero = true,
                            UserId = "c151a086-fe63-41ed-9fa0-1dcb43f7a556"
                        },
                        new
                        {
                            PlayerId = 3,
                            BiteCode = 10911,
                            GameId = 2,
                            IsHuman = false,
                            IsPatientZero = false,
                            UserId = "3885542f-5e69-4493-aef8-69a55ec152a3"
                        },
                        new
                        {
                            PlayerId = 4,
                            BiteCode = 18737,
                            GameId = 3,
                            IsHuman = true,
                            IsPatientZero = false,
                            UserId = "c8f391c6-2257-4ed0-bef2-f275bff089d2"
                        });
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.Squad", b =>
                {
                    b.Property<int>("SquadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHuman")
                        .HasColumnType("bit");

                    b.Property<string>("SquadName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SquadId");

                    b.HasIndex("GameId");

                    b.ToTable("Squad");

                    b.HasData(
                        new
                        {
                            SquadId = 1,
                            GameId = 1,
                            IsHuman = true,
                            SquadName = "Best squad ever"
                        },
                        new
                        {
                            SquadId = 2,
                            GameId = 2,
                            IsHuman = false,
                            SquadName = "Better than best squad"
                        },
                        new
                        {
                            SquadId = 3,
                            GameId = 1,
                            IsHuman = false,
                            SquadName = "Gang gang"
                        },
                        new
                        {
                            SquadId = 4,
                            GameId = 3,
                            IsHuman = true,
                            SquadName = "The beasts"
                        });
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.SquadCheckin", b =>
                {
                    b.Property<int>("SquadCheckinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<int>("SquadId")
                        .HasColumnType("int");

                    b.Property<int>("SquadMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SquadCheckinId");

                    b.HasIndex("GameId");

                    b.HasIndex("SquadId");

                    b.HasIndex("SquadMemberId");

                    b.ToTable("SquadCheckin");

                    b.HasData(
                        new
                        {
                            SquadCheckinId = 1,
                            EndTime = new DateTime(2022, 9, 15, 8, 20, 46, 67, DateTimeKind.Local).AddTicks(6908),
                            GameId = 1,
                            Lat = -26.66386,
                            Lng = 25.283757999999999,
                            SquadId = 1,
                            SquadMemberId = 1,
                            StartTime = new DateTime(2022, 9, 15, 8, 10, 46, 65, DateTimeKind.Local).AddTicks(1723)
                        },
                        new
                        {
                            SquadCheckinId = 2,
                            EndTime = new DateTime(2022, 9, 15, 8, 20, 46, 67, DateTimeKind.Local).AddTicks(8029),
                            GameId = 2,
                            Lat = -26.66386,
                            Lng = 25.283757999999999,
                            SquadId = 2,
                            SquadMemberId = 2,
                            StartTime = new DateTime(2022, 9, 15, 8, 10, 46, 67, DateTimeKind.Local).AddTicks(8021)
                        },
                        new
                        {
                            SquadCheckinId = 3,
                            EndTime = new DateTime(2022, 9, 15, 8, 20, 46, 67, DateTimeKind.Local).AddTicks(8035),
                            GameId = 2,
                            Lat = -26.66386,
                            Lng = 25.283757999999999,
                            SquadId = 2,
                            SquadMemberId = 2,
                            StartTime = new DateTime(2022, 9, 15, 8, 10, 46, 67, DateTimeKind.Local).AddTicks(8033)
                        });
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.SquadMember", b =>
                {
                    b.Property<int>("SquadMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("SquadId")
                        .HasColumnType("int");

                    b.HasKey("SquadMemberId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.HasIndex("SquadId");

                    b.ToTable("SquadMember");

                    b.HasData(
                        new
                        {
                            SquadMemberId = 1,
                            PlayerId = 3,
                            Rank = 4,
                            SquadId = 1
                        },
                        new
                        {
                            SquadMemberId = 2,
                            PlayerId = 2,
                            Rank = 5,
                            SquadId = 2
                        },
                        new
                        {
                            SquadMemberId = 3,
                            PlayerId = 4,
                            Rank = 1,
                            SquadId = 3
                        },
                        new
                        {
                            SquadMemberId = 4,
                            PlayerId = 1,
                            Rank = 10,
                            SquadId = 4
                        });
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = "c208f8b8-22bb-464c-93c9-0e011f4d827f",
                            FirstName = "Rebecka",
                            IsAdmin = false,
                            LastName = "Ocampo Sandgren"
                        },
                        new
                        {
                            UserId = "c151a086-fe63-41ed-9fa0-1dcb43f7a556",
                            FirstName = "Fadi",
                            IsAdmin = true,
                            LastName = "Akkaoui"
                        },
                        new
                        {
                            UserId = "3885542f-5e69-4493-aef8-69a55ec152a3",
                            FirstName = "Negin",
                            IsAdmin = false,
                            LastName = "Bakhtiarirad"
                        },
                        new
                        {
                            UserId = "c8f391c6-2257-4ed0-bef2-f275bff089d2",
                            FirstName = "Betiel",
                            IsAdmin = false,
                            LastName = "Yohannes"
                        });
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.Chat", b =>
                {
                    b.HasOne("HumansVsZombies_Backend.Models.Game", "Game")
                        .WithMany("Chats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HumansVsZombies_Backend.Models.Player", "Player")
                        .WithMany("Chats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HumansVsZombies_Backend.Models.Squad", "Squad")
                        .WithMany("Chats")
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Game");

                    b.Navigation("Player");

                    b.Navigation("Squad");
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.Kill", b =>
                {
                    b.HasOne("HumansVsZombies_Backend.Models.Game", "Game")
                        .WithMany("Kills")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HumansVsZombies_Backend.Models.Player", "Killer")
                        .WithMany("Kills")
                        .HasForeignKey("KillerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HumansVsZombies_Backend.Models.Player", "Victim")
                        .WithOne("Kill")
                        .HasForeignKey("HumansVsZombies_Backend.Models.Kill", "VictimId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Killer");

                    b.Navigation("Victim");
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.Mission", b =>
                {
                    b.HasOne("HumansVsZombies_Backend.Models.Game", "Game")
                        .WithMany("Missions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.Player", b =>
                {
                    b.HasOne("HumansVsZombies_Backend.Models.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumansVsZombies_Backend.Models.User", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.Squad", b =>
                {
                    b.HasOne("HumansVsZombies_Backend.Models.Game", "Game")
                        .WithMany("Squads")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.SquadCheckin", b =>
                {
                    b.HasOne("HumansVsZombies_Backend.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumansVsZombies_Backend.Models.Squad", "Squad")
                        .WithMany("SquadCheckins")
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HumansVsZombies_Backend.Models.SquadMember", "SquadMember")
                        .WithMany("SquadCheckins")
                        .HasForeignKey("SquadMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Squad");

                    b.Navigation("SquadMember");
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.SquadMember", b =>
                {
                    b.HasOne("HumansVsZombies_Backend.Models.Player", "Player")
                        .WithOne("SquadMember")
                        .HasForeignKey("HumansVsZombies_Backend.Models.SquadMember", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumansVsZombies_Backend.Models.Squad", "Squad")
                        .WithMany("SquadMembers")
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Squad");
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.Game", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Kills");

                    b.Navigation("Missions");

                    b.Navigation("Players");

                    b.Navigation("Squads");
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.Player", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Kill");

                    b.Navigation("Kills");

                    b.Navigation("SquadMember");
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.Squad", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("SquadCheckins");

                    b.Navigation("SquadMembers");
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.SquadMember", b =>
                {
                    b.Navigation("SquadCheckins");
                });

            modelBuilder.Entity("HumansVsZombies_Backend.Models.User", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
